### ISSUE TITLE
[Action] 	 Walmart Tech Workers In San Bruno Rally & Protest Gun Violence & Massacre SF Bay Area Indymedia Dozens of Walmart tech workers walked out to protest the continued sale of guns by WalMart 

### ISSUE THREAD

**Issue by organizejs** [organizejs/collective-actions-in-tech#132]
## A description of the event
Walmart Tech Workers In San Bruno Rally & Protest Gun Violence & MassacreSF Bay Area IndymediaDozens of Walmart tech workers walked out to protest the continued sale of guns by WalMart

## Links
https://www.indybay.org/newsitems/2019/08/07/18825265.php

**Comment by organizejs** [comment]
@nataliyaned does this count? what do you think

**Comment by nataliyaned** [comment]
I think it should. We counted Wayfair.
