### ISSUE TITLE
[Action] ubereats drivers unionize in japan

### ISSUE THREAD

**Issue by organizejs** [organizejs/collective-actions-in-tech#189]
https://www.japantimes.co.jp/news/2019/10/03/business/corporate-business/uber-eats-delivery-staff-japan-form-labor-union

**Comment by nataliyaned** [comment]
Also Foodora in Norway apparently:
https://www.vice.com/en_us/article/59nk8d/gig-workers-are-forming-the-worlds-first-food-delivery-app-unions

**Comment by organizejs** [comment]
ill create a separate issue for it
