### ISSUE TITLE
[Action] GitHub open letter to drop ICE

### ISSUE THREAD

**Issue by nataliyaned** [organizejs/collective-actions-in-tech#191]
https://www.washingtonpost.com/technology/2019/10/09/employees-ask-github-cancel-ice-contract-we-cannot-offset-human-lives-with-money/

https://www.washingtonpost.com/context/letter-from-github-employees-to-ceo-about-the-company-s-ice-contract/fb280de9-2bc3-40d5-b1a5-e3b954bf0d25/

**Comment by organizejs** [comment]
https://www.bloomberg.com/news/articles/2019-10-10/microsoft-employees-call-to-end-github-ice-contract

letter: https://github.com/MSWorkers/support.Githubbers

MSFT workers also wrote a letter to support githubbers. Separate line item?

**Comment by nataliyaned** [comment]
Hmmm. I'd say yes!
