### ISSUE TITLE
[Action] Google Zurich Office Holds Unionization Meeting

### ISSUE THREAD

**Issue by nataliyaned** [organizejs/collective-actions-in-tech#196]
https://www.vox.com/recode/2019/10/21/20924697/google-unionization-switzerland-zurich-syndicom-zooglers

**Comment by organizejs** [comment]
https://www.bloomberg.com/amp/news/articles/2019-10-21/swiss-google-employees-defy-managers-stage-labor-event?__twitter_impression=true
