### ISSUE TITLE
[Action] Protests at Draper Laboratories (1969 and 1982)

### ISSUE THREAD

**Issue by nataliyaned** [organizejs/collective-actions-in-tech#217]
http://credo.library.umass.edu/view/full/muph009-vHG-sl108-i001

https://www.thecrimson.com/article/1982/4/27/18-arrested-in-draper-lab-protest/

Mostly a military/space tech laboratory. Prominent work on missile guidance systems. 

Do you think this counts @organizejs ?

**Comment by organizejs** [comment]
Hmm i'm not sure - i think if we think Charles Stark Draper laboratories is a tech company, then it would make sense to add it. I suppose we need more guidelines around what counts as a 'tech company' vs what doesnt.
