### ISSUE TITLE
[Action] Onboarding Kit for Tech Labor Organizing (on Kickstarter)

### ISSUE THREAD

**Issue by nataliyaned** [organizejs/collective-actions-in-tech#222]
https://twitter.com/ClarissaRedwine/status/1194278095039213569?s=19

https://www.kickstarter.com/projects/clarissaredwine/solidarity-onboarding

**Comment by nataliyaned** [comment]
https://www.vice.com/en_us/article/d3aqkz/a-fired-kickstarter-organizer-is-trying-to-unionize-tech-workers-using-kickstarter

**Comment by organizejs** [comment]
hmm should this count since it is only 2 tech worker? In our contribution guidelines, we write `(1) "Collective". Must involve a minimum of two employees`
