### ISSUE TITLE
[Action] tech against facism in india

### ISSUE THREAD

**Issue by organizejs** [organizejs/collective-actions-in-tech#243]
https://twitter.com/SandeepMertia/status/1208416544952332289?s=19

**Comment by shushugah** [comment]
Also https://twitter.com/twc_bangalore/status/1207338500766543873

We, the members of the Tech Workers Coalition stand in solidarity with the students across India to exercise their fundamental right to dissent and we strongly condemn the Citizenship Amendment Act (CAA) and the National Registry of Citizens(NRC).

On December 15th, the Delhi Police forcefully entered the university defying authorities
and attacked the students. This has been confirmed by the Vice-Chancellor of Jamia Milia Islamia University.

Police broke into the library and mosque and fired tear gas shells. Hundreds of students were critically injured and forced to leave the campus. Several students were detained by the police and later released on 16th December 2019 after the mass protest by the
student community at Police Headquarters in Delhi. A similar crackdown was
observed at Aligarh Muslim University where the UP police violently attacked the students inside their hostel. UP Police unlawfully unleashed tear gas and lathi charge on the students. There was also a curfew and internet shutdown imposed at AMU.

The Citizenship Amendment Act of 2019 is fundamentally discriminatory and
unconstitutional. The Amendment allows religious minorities from Afghanistan, Pakistan and Bangladesh to acquire Indian citizenship while explicitly excluding Muslim migrants.

The Act undermines ideals of equality, dignity and respect guaranteed to all by the Constitution of India. If an Indian citizen is excluded under the NRC, if the person is a non-Muslim, then the person can claim citizenship under the CAA. However, if the person identifies as a Muslim, then the person will not be granted citizenship and sent to detention camps currently constructed in Assam and Karnataka. Simultaneously,
the passing of India's erroneous data protection law endangers the privacy and right to dissent of Indian citizens by affording the state illegitimate powers over our data in the name of national security.

While it is disheartening and enraging to see extremely violent uses of state forces to suppress student voices in the world’s ‘so called’ largest democracy in the world, we celebrate the courage demonstrated by the students and citizens raising voices of dissent. We lend our unconditional support and solidarity to the fearless and courageous students as they continue to protest the undemocratic actions against the students and the unconstitutional nature of the CAA and NRC!
