### ISSUE TITLE
[Action] Over 100 Residents of California’s Inland Empire Occupy Amazon Developer's Offices

### ISSUE THREAD

**Issue by organizejs** [organizejs/collective-actions-in-tech#253]
https://www.vice.com/amp/en_us/article/g5xvmy/over-100-residents-of-californias-inland-empire-occupy-amazon-developers-offices

**Comment by organizejs** [comment]
"But locals are concerned about the pollution and more grueling warehouse jobs coming to the area. On Wednesday, roughly 150 residents, labor organizers, **and former Amazon warehouse workers**—known collectively as San Bernardino Airport Communities protested at the offices of the developer Hillwood, chanting, playing drums, and waving banners reading: “AMAZON: WE DESERVE GOOD JOBS AND CLEAN AIR.” The Texas-based developer Hillwood is a favorite of Amazon’s. Recent projects include a regional Amazon air hub at Dallas/Fort Worth International Airport and a delivery center outside Chicago."
@nataliyaned should this count?

**Comment by nataliyaned** [comment]
This is a tough one. I'd go with "no" since we're specific about being employed within the last year on Contributing. The group doesn't seem to explicitly identify as former Amazon workers also.
