### ISSUE TITLE
[Action] protest against palantir on github

### ISSUE THREAD

**Issue by organizejs** [organizejs/collective-actions-in-tech#39]
https://www.fastcompany.com/90348304/exclusive-tech-workers-organize-protest-against-palantir-on-the-github-coding-platform

**Comment by bobwhitelock** [comment]
https://gist.github.com/noahzgordon/29af8c13106ddc591ccaa1ea0ce6af74

**Comment by organizejs** [comment]
@bobwhitelock would you like to make a PR for this? [contributing](https://github.com/organizejs/collective-actions-in-tech/blob/master/CONTRIBUTING.md)

**Comment by bobwhitelock** [comment]
@organizejs what would you want me to add in a PR? That link's mentioned in the original article in this issue, just mentioning it for easy reference 🙂

**Comment by organizejs** [comment]
@bobwhitelock yes gotcha. i meant to add to this repo's collection of tech actions.

**Comment by organizejs** [comment]
resolved commit 2f4de43
