### ISSUE TITLE
rethink data-fields

### ISSUE THREAD

**Issue by organizejs** [organizejs/collective-actions-in-tech#5]
rethink whether or not the `union affiliation` and `employment type` field is necessary

**Comment by organizejs** [comment]
Also whether we're missing any important fields...

**Comment by bentarnoff** [comment]
I like `union affiliation`, even tho most events probably won't have one, but I have mixed feelings about `employment type`. Not sure `employment type` is worth the overhead.

**Comment by bentarnoff** [comment]
`location` might be an interesting field, if a tricky one. 

certain events are highly localized (Palantir protest in Palo Alto), while others will have multiple locations (for example, Lanetix was headquartered in SF and DC). 

for other events we may simply have to give the name of the country, like Spain. and for the Google Walkout, we may have to simply say `worldwide`.

even with the above difficulties, i think `location` would be a worthwhile field.

**Comment by organizejs** [comment]
agreed, `location` would be great. It would let us do some cool mapping work too.

**Comment by organizejs** [comment]
so the fields we have are the following:

| field | categorical | categories | desc | 
| --- | --- | --- | --- |
| date | false | | earliest relevant date, format YYYY-MM-DD |
| source | false | | comma separated sources (urls) |
| company | false | | comma separated list of companies involved |
| action | true | strike, protest, petition, legal action, union representation, [TODO, what else?] | form of action taken | 
| ~~employment_type~~ | ~~true~~ | ~~fte, non-fte, unknown~~ | |
| ~~union_affiliation~~ | | | |
| worker_count | false | | number of workers, if a concrete number is not stated, lean on the conservative side | 
| struggle | true | wages, ethics, benefits, working conditions, [TODO, what else?] | reason for action | 
| location | false | | city | 
| description | false | | |
| notes | false | | _what can this be used for?_| 

some open questions:
- should protest even be a valid category for `action`
- in terms of `action` if kickstarter declares plans to unionize, but hasn't gotten union recognition yet, do we add it. And then if they do get union recognition, is that a new event entirely?
- i think i agree that `employment_type` may not be worth the overhead, but i am very interested in the growth of contract worker power vs fte (despite kickstarter's plans to unionize and stuff happening at google, i still think that our strategy to build worker power in tech should center contract workers) Maybe this can be a post processing step
- for amazon warehouse worker strike that happened over thanksgiving in 2018, there were a handful of discrete locations. Perhaps the way we handle this is simply doing a comma separated list of locations. BUT if another strike, with similar struggle happened a week later, we would make it a distinct event. is that what you had in mind? If so, we're making the claim that events are date-bound in a way. 
- i think we should add `struggle` back in. action only ever comes from struggle. I think we need to figure out what the valid categories are though.
- any requirements for `descriptions` or `notes`?

**Comment by bentarnoff** [comment]
some replies:

* yes, i think `protest` is a valid category for `action`, because tech workers have participated in protests outside of tech offices, such as Salesforce

* yes, i think announcing a union drive should be a distinct action from winning union recognition. 

* i agree about the desirability of tracking the growth of contract worker actions vs FTEs. i wonder if one approach could be to use the `notes` category as a place where we could add certain tags. so `contract workers` could be a tag we include in the `notes` category if the action involved contract workers. (there would presumably be other tags for other things we want to track too.)

* yes, i think distinct strikes should be treated as distinct events. however, does the `date` category accept a range? that might be useful, since events can occur over multiple days.

* yes, i think `struggle` is useful, and i think the categories you have are a good start

* as above, it might make sense to treat `notes` as a tags category. we could even rename it to `tags` or something along those lines. as for `descriptions`, i like how you're using it now. although it might make sense to set guidelines for external contributors, like, "1-2 sentence description of event."

**Comment by organizejs** [comment]
i'll do an initial pass on the dataset based on the above and update/delete with these new fields.

**Comment by organizejs** [comment]
Here's what i'm updating it to:

| field | type | desc | 
| --- | --- | --- |
| date | datetime| earliest relevant date, format YYYY-MM-DD |
| source | urls | comma separated sources (urls) |
| company | str | comma separated list of companies involved |
| action | [strike, protest, petition, legal_action, union_drive, union_representation] | form of action taken | 
| worker_count | int | number of workers, if a concrete number is not stated, lean on the conservative side | 
| struggle | [ethics, pay_and_benefits, working_conditions] | reason for action | 
| location | str | city | 
| description | str | short description about the event |
| tags | str | other data to track |

**Comment by organizejs** [comment]
what would you categorize struggle type for the union drive at kickstarter? working_conditions?

**Comment by organizejs** [comment]
what would you do about this one: https://medium.com/s/story/an-open-letter-to-microsoft-dont-bid-on-the-us-military-s-project-jedi-7279338b7132

Its an open letter, but not technically a petition since it did not collect signatures. include? and if so, what is the `action`

**Comment by organizejs** [comment]
Having a lot of issues with these fields... but i'd rather spend the time to make it right than to move fast and have to update it after. So now i'm thinking we restructure the data schema. Mandatory fields remain as fields, and optional fields go into a dictionary inside of 'tags' like so:

| field | type | desc | required |
| --- | --- | --- | --- |
| date | datetime| earliest relevant date, format YYYY-MM-DD | True |
| source | urls | comma separated sources (urls) | True |
| action | [strike, protest, petition, legal_action, union_drive, union_representation] | form of action taken | True |
| struggle | [ethics, pay_and_benefits, working_conditions, discrimination, unfair_labor_practice, job_security] | reason for action |  True |
| description | str | short description about the event | True |
| tags | str | TagDictionary |  False |

TagDictionary:

| tag-key | tag-value |
| --- | --- |
| location | online, worldwide, or a country are also acceptable |
| company | comma separated list of companies involved | 
| worker_count | number of workers, if a concrete number is not stated, lean on the conservative side |
| duration | number of days the action lasted for |

---

An example would be like:
<table data-author="organizejs">
  <tr>
   <td class="field-key">
    date
   </td>
   <td class="field-value">
    2019-04-02
   </td>
  </tr>
  <tr>
   <td class="field-key">
    source
   </td>
   <td class="field-value">
    <a href="https://www.theguardian.com/technology/2019/apr/02/google-workers-sign-letter-temp-contractors-protest">
     The Guardian
    </a>
   </td>
  </tr>
  <tr>
   <td class="field-key">
    action
   </td>
   <td class="field-value">
    petition
   </td>
  </tr>
  <tr>
   <td class="field-key">
    struggle
   </td>
   <td class="field-value">
    working_conditions, pay_and_benefits
   </td>
  </tr>
  <tr>
   <td class="field-key">
    description
   </td>
   <td class="field-value">
    More than 900 Google workers have signed a letter objecting to the tech giant's treatment of temporary contractors, in what organizers are calling a "historical coalition" between Google"s full-time employees (FTEs) and temps, vendors and contractors (TVCs).
   </td>
  </tr>
  <tr>
   <td class="field-key">
    tags
   </td>
   <td class="field-value">
    { <br>"companies": ["Google"], <br>"locations": ["worldwide"], <br>"worker_count": 10000, <br>"duration": 1 <br>}
   </td>
  </tr>
 </table>

**Comment by organizejs** [comment]
closing issue, no longer relevant
