### ISSUE TITLE
consider scope of actions

### ISSUE THREAD

**Issue by organizejs** [organizejs/collective-actions-in-tech#6]
'Tech workers' are too broad. Nearly everyone is a 'tech worker'. Do we change the scoping to be any kind of tech related protests?

For example, should the amazon hq protest be included since it were largely driven by the residents (as opposed to tech workers)? Or should it be more centered around worker power, so only select events/actions that involve workers fighting agaisnt their bosses?

**Comment by bentarnoff** [comment]
submitted a PR to help clarify "tech industry": https://github.com/organizejs/collective-actions-in-tech/pull/8

fwiw, I don't think the HQ2 protest should be included. ditto with the [medium post](https://medium.com/@bu64dcjrytwitb8/on-recent-research-auditing-commercial-facial-analysis-technology-19148bda1832?fbclid=IwAR1Uwyfv8da3OSgnNS1Nm3takYuDG1ks5jelJYwjImutVT5UnJ3RrpYIpEw) by the "concerned researchers" re: Rekognition. i think we should narrow scope to actions taken by workers within the tech industry, as we're defining it.

**Comment by organizejs** [comment]
sounds good
