### ISSUE TITLE
[Action] Portland Postmates Workers to Join National Protest of Pay Cut by Only Accepting Surge-Price Deliveries

### ISSUE THREAD

**Issue by organizejs** [organizejs/collective-actions-in-tech#86]
## A description of the event
Portland Postmates Workers to Join National Protest of Pay Cut by Only Accepting Surge-Price Deliveries

## Links
https://www.wweek.com/news/2019/06/13/portland-postmates-workers-to-join-national-protest-of-pay-cut-by-only-accepting-surge-price-deliveries/

**Comment by nataliyaned** [comment]
https://github.com/organizejs/collective-actions-in-tech/blob/master/actions/0085.md
