### ISSUE TITLE
add action, evaluate experience

### ISSUE THREAD

**Issue by organizejs** [organizejs/collective-actions-in-tech#9]
@bentarnoff can you try adding an event and see if the experience of adding an event is reasonable

**Comment by bentarnoff** [comment]
i found the brief summary of how to contribute a bit confusing, so i just replaced it with a link out to `CONTRIBUTING.MD`, which i think is a lot clearer: https://github.com/organizejs/collective-actions-in-tech/pull/10.

the workflow is doable, and i think totally fine for our purposes. might want to explore the idea of having some kind of form at a later date though.

**Comment by organizejs** [comment]
cool. approved your pr. i'll close this issue and make another one for a form
